name: Publish Nodes
on:
  push:
    branches:
    - main
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: use node 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run lint
    - run: npm run compile
    - name: Publish to production
      run: npm run publish:nodes
      env:
        NODESCRIPT_API_URL: https://api.nodescript.dev
        NODESCRIPT_API_TOKEN: ${{ secrets.NODESCRIPT_API_TOKEN_PRODUCTION }}
        NODESCRIPT_WORKSPACE_ID: o5TlexFG23iGsQOI
